### ISSUE TITLE
Assumes that input date has same timezone as now

### ISSUE THREAD

**Issue by raydavis** [doz/time_zone_ext#4]
Thanks for the great write-up at http://danilenko.org/2012/7/6/rails_timezones/ and this sample code. Unfortunately, it does not seem to take transitions in daylight-savings-time into account. For example, my Rails application is running in California, and therefore is currently on Pacific Standard Time. In June, however, California was on PDT. When I parse a Z-less date-time string from June, I get a result which is one hour off (reflecting standard time rather than daylight savings).

This code appears to do the job for me:

```
    if format =~ /%z/i
      DateTime.strptime(date_time_string, format)
    else
      parsed_time = Time.strptime(date_time_string, format)
      time_in_zone = ActiveSupport::TimeWithZone.new(nil, Time.zone, parsed_time)
      time_in_zone.to_datetime
    end
```

**Comment by princejoseph** [comment]
@raydavis I have wrapped up this code in PR https://github.com/doz/time_zone_ext/pull/6. Thanks a lot @raydavis for the code.

I have also covered this in specs so as to avoid regression bugs. (In the process, learned a lot about Ruby gem management :) ) 

@doz Thanks once again for the gem and the great write up http://danilenko.org/2012/7/6/rails_timezones/

**Comment by raydavis** [comment]
Thanks for testing it & getting it in, @princejoseph !

**Comment by doz** [comment]
Thanks guys for addressing this! And thanks @princejoseph for updated specs and configs, really appreciate this. Sorry for not getting to this earlier.
